
from pydantic import JsonValue

from hamoon.infrastructure.ai.contracts import (
    AITaskClass,
    ProviderStructuredRequest,
    ProviderStructuredResponse,
)


class FakeAIProvider:
    code = "FAKE"

    async def generate_structured(
        self,
        request: ProviderStructuredRequest,
    ) -> ProviderStructuredResponse:
        if request.task_class is not AITaskClass.DIAGNOSIS:
            raise ValueError("Fake provider currently supports DIAGNOSIS only.")

        bottlenecks = request.features.get("pgor.bottleneck_variables", [])
        if not isinstance(bottlenecks, list):
            bottlenecks = []

        output: dict[str, JsonValue] = {
            "schema_version": "diagnosis-v1",
            "summary": "Test-only structured diagnosis proposal.",
            "items": [
                {
                    "code": f"PGOR_BOTTLENECK_{value}",
                    "category": "NEED",
                    "title": f"Review PGOR bottleneck {value}",
                    "rationale": (
                        "Generated by FakeAIProvider for deterministic contract testing."
                    ),
                    "supporting_feature_refs": ["pgor.bottleneck_variables"],
                    "uncertainty": "UNKNOWN",
                }
                for value in bottlenecks
                if isinstance(value, str)
            ],
            "review_flags": ["FAKE_PROVIDER", "HUMAN_REVIEW_REQUIRED"],
        }
        return ProviderStructuredResponse(
            provider_code=self.code,
            model_id=request.model_id,
            output=output,
        )
